server:
  command: "php http/walnut_worker.php"
  relay: "pipes"

http:
  address: 0.0.0.0:8084
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

version: "3"
